# Database buku untuk rekomendasi
# Format: book_id, title, theme
books = [
    {"book_id": 1, "title": "Pemrograman Python Dasar", "theme": "Teknologi"},
    {"book_id": 2, "title": "Belajar Data Science", "theme": "Teknologi"},
    {"book_id": 3, "title": "Kecerdasan Buatan Modern", "theme": "Teknologi"},
    {"book_id": 4, "title": "Dasar-dasar Machine Learning", "theme": "Teknologi"},
    {"book_id": 5, "title": "Statistika untuk Pemula", "theme": "Matematika"},
    {"book_id": 6, "title": "Aljabar Linear Praktis", "theme": "Matematika"},
    {"book_id": 7, "title": "Kalkulus Mudah", "theme": "Matematika"},
    {"book_id": 8, "title": "Logika dan Algoritma", "theme": "Teknologi"},
    {"book_id": 9, "title": "Sejarah Indonesia", "theme": "Sejarah"},
    {"book_id": 10, "title": "Perang Dunia II", "theme": "Sejarah"},
    {"book_id": 11, "title": "Ekonomi Mikro", "theme": "Ekonomi"},
    {"book_id": 12, "title": "Ekonomi Makro", "theme": "Ekonomi"},
    {"book_id": 13, "title": "Manajemen Bisnis", "theme": "Ekonomi"},
    {"book_id": 14, "title": "Investasi Saham", "theme": "Ekonomi"},
    {"book_id": 15, "title": "Psikologi Dasar", "theme": "Psikologi"},
    {"book_id": 16, "title": "Psikologi Anak", "theme": "Psikologi"},
    {"book_id": 17, "title": "Psikologi Remaja", "theme": "Psikologi"},
    {"book_id": 18, "title": "Pengembangan Diri", "theme": "Motivasi"},
    {"book_id": 19, "title": "Motivasi Sukses", "theme": "Motivasi"},
    {"book_id": 20, "title": "Kepemimpinan Efektif", "theme": "Motivasi"},
    {"book_id": 21, "title": "Filsafat Barat", "theme": "Filsafat"},
    {"book_id": 22, "title": "Filsafat Timur", "theme": "Filsafat"},
    {"book_id": 23, "title": "Etika dan Moral", "theme": "Filsafat"},
    {"book_id": 24, "title": "Seni Lukis Modern", "theme": "Seni"},
    {"book_id": 25, "title": "Seni Musik Dunia", "theme": "Seni"},
    {"book_id": 26, "title": "Seni Tari Tradisional", "theme": "Seni"},
    {"book_id": 27, "title": "Novel Petualangan", "theme": "Fiksi"},
    {"book_id": 28, "title": "Novel Romantis", "theme": "Fiksi"},
    {"book_id": 29, "title": "Cerpen Inspiratif", "theme": "Fiksi"},
    {"book_id": 30, "title": "Puisi Kehidupan", "theme": "Fiksi"},
    {"book_id": 31, "title": "Teknik Sipil Dasar", "theme": "Teknik"},
    {"book_id": 32, "title": "Teknik Mesin Modern", "theme": "Teknik"},
    {"book_id": 33, "title": "Teknik Elektro", "theme": "Teknik"},
    {"book_id": 34, "title": "Teknik Kimia", "theme": "Teknik"},
    {"book_id": 35, "title": "Kesehatan Masyarakat", "theme": "Kesehatan"},
    {"book_id": 36, "title": "Gizi dan Nutrisi", "theme": "Kesehatan"},
    {"book_id": 37, "title": "Farmasi Dasar", "theme": "Kesehatan"},
    {"book_id": 38, "title": "Ilmu Kedokteran", "theme": "Kesehatan"},
    {"book_id": 39, "title": "Astronomi untuk Pemula", "theme": "Sains"},
    {"book_id": 40, "title": "Fisika Modern", "theme": "Sains"},
    {"book_id": 41, "title": "Kimia Dasar", "theme": "Sains"},
    {"book_id": 42, "title": "Biologi Sel", "theme": "Sains"},
    {"book_id": 43, "title": "Geografi Dunia", "theme": "Sains"},
    {"book_id": 44, "title": "Matematika Diskrit", "theme": "Matematika"},
    {"book_id": 45, "title": "Statistika Lanjut", "theme": "Matematika"},
    {"book_id": 46, "title": "Ekonomi Internasional", "theme": "Ekonomi"},
    {"book_id": 47, "title": "Psikologi Sosial", "theme": "Psikologi"},
    {"book_id": 48, "title": "Seni Rupa Kontemporer", "theme": "Seni"},
    {"book_id": 49, "title": "Novel Misteri", "theme": "Fiksi"},
    {"book_id": 50, "title": "Puisi Cinta", "theme": "Fiksi"}
]
